version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: loopit-mysql
    restart: always
    environment:
      MYSQL_DATABASE: loopit
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--performance-schema=off"
      - "--innodb-buffer-pool-size=64M"
      - "--max-connections=50"
      - "--table-open-cache=200"

  backend:
    image: loopit543/loopit-backend:latest
    container_name: loopit-backend
    restart: always
    env_file:
      - .env.test
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
