version: "3.9"

services:
  app:
    image: loopit543/loopit-dev:latest
    container_name: loopit-dev-app
    env_file:
      - .env.test
    restart: "no"
    ports:
      - "8081:8080"
    environment:
      # application.yml 적용 후 application-dev.yml 적용.
      SPRING_PROFILES_ACTIVE: dev
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      TZ: Asia/Seoul
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: loopit-mysql
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: loopit
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--performance-schema=off"
      - "--innodb-buffer-pool-size=64M"
      - "--max-connections=50"
      - "--table-open-cache=200"

volumes:
  mysql-data:
