name: CI/CD - Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  # CI: Build & Image Push
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: application.yml 파일 설정
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 4. Docker Hub 로그인
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 5. Docker 이미지 빌드 & 푸시
      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/loopit-dev:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/loopit-dev:latest

  # CD: Deploy to EC2
  cd:
    runs-on: ubuntu-latest
    needs: ci   # CI 성공해야 CD 실행됨

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_TEST }}" > .env.test

      - name: .env 파일 EC2에 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ".env.test"
          target: "/home/ubuntu/loopit-dev/docker/"


      - name: Check docker-compose.dev.yml exists
        run: ls -al ./docker/

      # 6. docker-compose.dev.yml EC2로 전송
      - name: Copy docker-compose.dev.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./docker/docker-compose.dev.yml"
          target: "/home/ubuntu/loopit-dev/docker/"

      # 7. EC2에서 컨테이너 재기동
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/loopit-dev/docker/
            docker compose -f docker-compose.dev.yml down
            docker compose -f docker-compose.dev.yml pull
            docker compose -f docker-compose.dev.yml up -d
