name: CI/CD Dev

on:
  push:
    branches: ["develop"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
       # GitHub 저장소 코드 가져오기
      - name: 1. Checkout source
        uses: actions/checkout@v4

      # JDK 설치(version 21)
      - name: 2. Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      # ./src/main/resources/ < 디렉토리에 application.yml 생성
      - name: 3. Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: 4. Gradle Wrapper 실행 권한 부여
        run: chmod +x gradlew

      - name: 5. Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 6. Build jar
        run: ./gradlew clean build -x test

      - name: 7. Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 8. Docker image Push
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/server:latest

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout source code
        uses: actions/checkout@v4

      - name: 2. Create .env file
        run: |
          echo "${{ secrets.ENV_TEST}}" > .env


      - name: 2-1. .env 파일 EC2에 전송
        uses: appleboy/scp-action@master # <= scp 명령어 실행
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ".env"
          target: "/home/ubuntu/loopit-dev/docker/"


      - name: Check docker-compose.dev.yml exists
        run: ls -al ./docker/

      - name: 3. docker-compose.yml 전달
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./docker/docker-compose.dev.yml"
          target: "/home/ubuntu/loopit-dev/docker/"  # <= 경로 일치시킴


      - name: 4. SSH 접속하여 EC2서버에 배포 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/loopit-dev/docker/
            docker pull ${{ secrets.DOCKER_USERNAME }}/server:latest
            docker compose -f docker-compose.dev.yml down
            docker compose -f docker-compose.dev.yml up -d
