name: CI/CD - LOOPIT Backend (Develop)

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t loopit543/loopit-backend:develop .
          docker push loopit543/loopit-backend:develop

      - name: Deploy to EC2 (Develop)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/loopit
            docker pull loopit543/loopit-backend:develop
            echo "${{ secrets.ENV_TEST }}" | base64 -d > .env.test
            docker-compose down
            docker-compose up -d
